### ISSUE TITLE
Im getting "An internal error occurred while attempting this command"

### ISSUE THREAD

**Issue by KritoKiller** [itsnewtjam/newtShop-Issues#38]
I keep getting this error when I perform the /sellchest and /sellwand command along with the /slimeradar on newtslime. Everything else works perfectly but I keep getting theses errors.

**Comment by itsnewtjam** [comment]
Could you send over the full error from console?

**Comment by KritoKiller** [comment]
[16:53:05] [Server thread/INFO]: KritoKiller issued server command: /slimeradar
[16:53:05] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'slimeradar' in plugin newtSlime v1.2.0
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot.jar:git-Spigot-800b93f-8160e29]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot.jar:git-Spigot-800b93f-8160e29]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:711) ~[spigot.jar:git-Spigot-800b93f-8160e29]
        at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1657) ~[spigot.jar:git-Spigot-800b93f-8160e29]
        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1497) ~[spigot.jar:git-Spigot-800b93f-8160e29]
        at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[spigot.jar:git-Spigot-800b93f-8160e29]
        at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot.jar:git-Spigot-800b93f-8160e29]
        at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot.jar:git-Spigot-800b93f-8160e29]
        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) [spigot.jar:git-Spigot-800b93f-8160e29]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot.jar:git-Spigot-800b93f-8160e29]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot.jar:git-Spigot-800b93f-8160e29]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot.jar:git-Spigot-800b93f-8160e29]
        at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:918) [spigot.jar:git-Spigot-800b93f-8160e29]
        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:911) [spigot.jar:git-Spigot-800b93f-8160e29]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [spigot.jar:git-Spigot-800b93f-8160e29]
        at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:895) [spigot.jar:git-Spigot-800b93f-8160e29]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:828) [spigot.jar:git-Spigot-800b93f-8160e29]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
Caused by: java.lang.NoSuchMethodError: com.newtjam.newtLib.newtGui.gui.Gui.<init>(ILjava/lang/String;)V
        at com.newtjam.newtSlime.gui.SlimeRadarGui.<init>(SlimeRadarGui.java:22) ~[?:?]
        at com.newtjam.newtSlime.commands.SlimeRadar.onCommand(SlimeRadar.java:22) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot.jar:git-Spigot-800b93f-8160e29]
        ... 17 more

**Comment by KritoKiller** [comment]
It looks like the /sellchest and /sellwand command are working now. But the slimeradar still gives me the error

**Comment by itsnewtjam** [comment]
Thanks! I'll push an update for newtSlime that should take care of it. In the meantime if you get errors with /sellchest or /sellwand again in the future let me know!

**Comment by KritoKiller** [comment]
Thank you! Will do!
